# Generated by Django 6.0.4 on 2026-04-23 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the employee as per records', max_length=255)),
                ('employee_id', models.CharField(db_index=True, help_text='Unique employee identification number', max_length=50, unique=True)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings for the period', max_digits=15)),
                ('free_service_count', models.PositiveIntegerField(default=0, help_text='Number of FREE services completed')),
                ('paid_service_count', models.PositiveIntegerField(default=0, help_text='Number of PAID services completed')),
                ('rr_service_count', models.PositiveIntegerField(default=0, help_text='Number of RR services completed')),
                ('wheel_alignment_lathe', models.DecimalField(decimal_places=2, default=0.0, help_text='Earnings or metrics from Wheel Alignment/Lathe work', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this employee record is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Branch where the employee is stationed', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.branch')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['employee_id', 'branch'], name='employees_e_employe_728f2f_idx')],
            },
        ),
    ]
