# Generated by Django 6.0 on 2026-04-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_email_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gross_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Gross earnings from the uploaded sheet', max_digits=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Net earnings after deductions (Wheel Alignment/Lathe + Water Service)', max_digits=15),
        ),
    ]
