# Generated by Django 6.0.4 on 2026-04-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_gross_earning_alter_employee_total_earning'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_employe_728f2f_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
