# Generated by Django 6.0 on 2026-04-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_remove_employee_employees_e_employe_728f2f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date this performance data refers to.')),
                ('free', models.IntegerField(default=0, help_text='Number of free services')),
                ('paid', models.IntegerField(default=0, help_text='Number of paid services')),
                ('rr', models.IntegerField(default=0, help_text='Number of RR (Return/Repair) services')),
                ('wheel_alignment_lathe', models.IntegerField(default=0, help_text='Number of wheel alignment or lathe tasks', verbose_name='Wheel Alignment / Lathe')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings for the period', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='The employee this data belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Record',
                'verbose_name_plural': 'Performance Records',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
