# Generated by Django 6.0 on 2026-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancerecord',
            name='leave_status',
            field=models.CharField(choices=[('P', 'Present'), ('L', 'Leave')], default='P', help_text='Attendance status from Labor Report (P/L)', max_length=10),
        ),
    ]
