# Generated by Django 6.0 on 2026-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_performancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancerecord',
            name='actual_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Actual earnings after deductions (Wheel Alignment + Service Deductions)', max_digits=12, verbose_name='Net Earnings'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings for the period (Gross)', max_digits=12, verbose_name='Gross Earnings'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='wheel_alignment_lathe',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount for wheel alignment or lathe tasks', max_digits=12, verbose_name='Wheel Alignment / Lathe'),
        ),
    ]
