# Generated by Django 6.0 on 2026-04-24 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_performancerecord_actual_earnings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('labour', 'Labour Incentive'), ('load_growth', 'Load Growth'), ('conversion', 'Conversion')], default='labour', max_length=20)),
                ('min_load', models.IntegerField(default=0, help_text='Minimum load required for this slab (e.g., 150)')),
                ('max_load', models.IntegerField(default=999999, help_text='Maximum load for this slab')),
                ('min_achievement_percent', models.DecimalField(decimal_places=2, help_text='Minimum achievement % required (e.g., 110 for 110%)', max_digits=6)),
                ('incentive_percent', models.DecimalField(decimal_places=2, help_text='Percentage of Labour Achieved to be given as incentive (e.g., 2.0)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incentive Rule',
                'verbose_name_plural': 'Incentive Rules',
                'ordering': ['min_load', '-min_achievement_percent'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The month this target applies to (first day of month)')),
                ('target_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('category', models.CharField(default='labour', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Target',
                'verbose_name_plural': 'Employee Targets',
                'unique_together': {('employee', 'month', 'category')},
            },
        ),
    ]
