# Generated by Django 6.0 on 2026-04-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_incentiverule_employeetarget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incentiverule',
            options={'ordering': ['min_load', 'category', '-min_threshold'], 'verbose_name': 'Incentive Rule', 'verbose_name_plural': 'Incentive Rules'},
        ),
        migrations.RemoveField(
            model_name='incentiverule',
            name='incentive_percent',
        ),
        migrations.RemoveField(
            model_name='incentiverule',
            name='min_achievement_percent',
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='is_deduction',
            field=models.BooleanField(default=False, help_text='True if this is a penalty/deduction (e.g., degrowth penalty).'),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='is_percentage',
            field=models.BooleanField(default=False, help_text='True if the reward is a percentage, False if it is a fixed ₹ amount.'),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='max_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional maximum threshold', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='min_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum threshold for the condition (e.g., 110 for 110% achievement, or 10500 for Per Vehicle)', max_digits=10),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed incentive amount in ₹ (if applicable)', max_digits=12),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='reward_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage reward (e.g., 2.0 for 2% of labour, or 15 for 15% deduction)', max_digits=5),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='bs_load',
            field=models.IntegerField(default=0, help_text='Total Body Shop Load (used to determine incentive slab: ABOVE/BELOW 150)'),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='conversion_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service to BodyShop conversion percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='load_growth_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Growth percentage compared to last month/target', max_digits=6),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='per_vehicle_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average labor amount per vehicle', max_digits=12),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='category',
            field=models.CharField(choices=[('labour', 'Labour Incentive (%)'), ('load_growth', 'Load Growth (Amount/%)'), ('per_vehicle', 'Per Vehicle (Amount)'), ('conversion', 'Service to BodyShop Conversion')], default='labour', max_length=30),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='max_load',
            field=models.IntegerField(default=999999, help_text='Maximum BS Load for this slab (e.g., 150 or 999999)'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='min_load',
            field=models.IntegerField(default=0, help_text='Minimum BS Load required for this slab (e.g., 0 or 151)'),
        ),
    ]
