# Generated by Django 6.0 on 2026-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_incentiverule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incentiverule',
            options={'ordering': ['load_slab', 'category', '-min_threshold'], 'verbose_name': 'Incentive Rule', 'verbose_name_plural': 'Incentive Rules'},
        ),
        migrations.RemoveField(
            model_name='incentiverule',
            name='max_load',
        ),
        migrations.RemoveField(
            model_name='incentiverule',
            name='min_load',
        ),
        migrations.RemoveField(
            model_name='performancerecord',
            name='bs_load',
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='load_slab',
            field=models.CharField(choices=[('ABOVE', 'Above 150'), ('BELOW', 'Below 150')], default='BELOW', help_text='Which load slab does this rule apply to?', max_length=10),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='is_above_150',
            field=models.BooleanField(default=False, help_text='Set to True if BS Load is Above 150, False if Below 150 (Uploaded as Yes/No)'),
        ),
    ]
