# Generated by Django 6.0.4 on 2026-04-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_incentiverule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancerecord',
            name='conversion_percent',
        ),
        migrations.RemoveField(
            model_name='performancerecord',
            name='load_growth_percent',
        ),
        migrations.RemoveField(
            model_name='performancerecord',
            name='per_vehicle_amount',
        ),
    ]
