# Generated by Django 6.0.4 on 2026-04-24 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_performancerecord_conversion_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_slab', models.CharField(choices=[('ABOVE', 'Above 150'), ('BELOW', 'Below 150')], default='BELOW', help_text='Above 150 or Below 150', max_length=10)),
                ('min_achievement_percent', models.DecimalField(decimal_places=2, help_text='Threshold percentage (e.g., 110 for 110% achievement)', max_digits=6)),
                ('incentive_percent', models.DecimalField(decimal_places=2, help_text='Incentive percentage (e.g., 2 for 2% of actual earnings)', max_digits=6)),
            ],
            options={
                'verbose_name': 'Incentive Slab',
                'verbose_name_plural': 'Incentive Slabs',
                'ordering': ['load_slab', '-min_achievement_percent'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The first day of the month this target applies to.')),
                ('target_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Target',
                'verbose_name_plural': 'Monthly Targets',
                'unique_together': {('employee', 'month')},
            },
        ),
        # Using SeparateDatabaseAndState because the tables might already be missing from DB
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='employeetarget',
                    name='employee',
                ),
                migrations.DeleteModel(
                    name='IncentiveRule',
                ),
                migrations.DeleteModel(
                    name='EmployeeTarget',
                ),
            ]
        ),
    ]
