# Generated by Django 6.0 on 2026-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_incentiveslab_monthlytarget_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlytarget',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='month',
            field=models.DateField(help_text='The first day of the month this target applies to.', unique=True),
        ),
        migrations.RemoveField(
            model_name='monthlytarget',
            name='employee',
        ),
    ]
