# Generated by Django 6.0 on 2026-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_monthlytarget_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentiveslab',
            name='load_slab',
            field=models.CharField(choices=[('ABOVE', 'Above 150'), ('BELOW', 'Below 150'), ('BOTH', 'Both')], default='BELOW', help_text='Above 150 or Below 150', max_length=10),
        ),
    ]
