# Generated by Django 6.0 on 2026-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_incentiveslab_load_slab'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentiveslab',
            name='max_achievement_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional maximum achievement percentage (e.g., 89 for 80-89% range)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='incentiveslab',
            name='incentive_percent',
            field=models.DecimalField(decimal_places=2, help_text='Incentive percentage (e.g., 2 for 2% of target amount)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='incentiveslab',
            name='min_achievement_percent',
            field=models.DecimalField(decimal_places=2, help_text='Minimum achievement percentage (e.g., 80)', max_digits=6),
        ),
    ]
