# Generated by Django 6.0 on 2026-04-24 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_incentiveslab_max_achievement_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The first day of the month for this calculation.')),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('achievement_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('incentive_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('incentive_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('slab_type', models.CharField(max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Incentive',
                'verbose_name_plural': 'Monthly Incentives',
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
