# Generated by Django 6.0 on 2026-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_monthlyincentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyincentive',
            name='efficiency_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='total_vehicles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='vehicle_count',
            field=models.IntegerField(default=0, help_text='Total services (Free + Paid + RR)'),
        ),
    ]
