# Generated by Django 6.0 on 2026-04-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_monthlyincentive_efficiency_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyincentive',
            name='degrowth_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='load_growth_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='load_growth_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
