# Generated by Django 6.0 on 2026-04-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_monthlyincentive_degrowth_deduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyincentive',
            name='degrowth_deduction',
        ),
    ]
