# Generated by Django 6.0.4 on 2026-04-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_remove_monthlyincentive_degrowth_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyincentive',
            name='load_growth_bonus',
        ),
        migrations.RemoveField(
            model_name='monthlyincentive',
            name='load_growth_percent',
        ),
    ]
