# Generated by Django 6.0 on 2026-04-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_remove_monthlyincentive_load_growth_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadGrowthSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_slab', models.CharField(choices=[('ABOVE', 'Above 150'), ('BELOW', 'Below 150'), ('BOTH', 'Both')], default='BOTH', help_text='Above 150, Below 150, or Both', max_length=10)),
                ('min_growth_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum growth percentage (e.g., 5.00 for 5%)', max_digits=6, null=True)),
                ('max_growth_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum growth percentage (e.g., 9.99)', max_digits=6, null=True)),
                ('incentive_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed bonus amount for this growth tier', max_digits=12)),
                ('deduction_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage deduction from eligible incentive (used for degrowth, e.g., 15)', max_digits=6)),
            ],
            options={
                'verbose_name': 'Load Growth Slab',
                'verbose_name_plural': 'Load Growth Slabs',
                'ordering': ['load_slab', '-min_growth_percent'],
            },
        ),
    ]
